CREATE TABLE project_main_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE project_sections ADD COLUMN main_section_id BIGINT REFERENCES project_main_sections(id) ON DELETE CASCADE;

-- Auto-migrate existing sections into a default "General" main section
DO $$
DECLARE
    p_record RECORD;
    new_main_id BIGINT;
BEGIN
    FOR p_record IN SELECT id FROM projects LOOP
        IF EXISTS (SELECT 1 FROM project_sections WHERE project_id = p_record.id AND main_section_id IS NULL) THEN
            INSERT INTO project_main_sections (project_id, name, order_index)
            VALUES (p_record.id, 'General Sections', 0)
            RETURNING id INTO new_main_id;
            
            UPDATE project_sections
            SET main_section_id = new_main_id
            WHERE project_id = p_record.id AND main_section_id IS NULL;
        END IF;
    END LOOP;
END $$;
