-- ============================================================
-- PRICE HISTORY TABLE
-- Tracks every price change on any part table
-- Run in Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS part_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_table_name TEXT NOT NULL,        -- e.g. 'mechanical_manufacture'
  part_id BIGINT NOT NULL,              -- FK to the part row
  part_number TEXT NOT NULL,            -- denormalized for fast lookup
  old_price NUMERIC(18, 2),
  new_price NUMERIC(18, 2) NOT NULL,
  old_currency TEXT,
  new_currency TEXT NOT NULL DEFAULT 'INR',
  old_discount_percent NUMERIC(5, 2),
  new_discount_percent NUMERIC(5, 2),
  change_reason TEXT,                   -- 'manual_edit', 'json_import', 'update_master', etc.
  changed_by TEXT,                      -- user email from auth context
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX idx_pph_part ON part_price_history(part_table_name, part_id);
CREATE INDEX idx_pph_part_number ON part_price_history(part_number);
CREATE INDEX idx_pph_date ON part_price_history(changed_at DESC);

-- Comments
COMMENT ON TABLE part_price_history IS 'Audit trail of all price changes across part tables';
COMMENT ON COLUMN part_price_history.part_table_name IS 'Source table: mechanical_manufacture, mechanical_bought_out, etc.';
COMMENT ON COLUMN part_price_history.change_reason IS 'What triggered the change: manual_edit, json_import, update_master, po_receive';

-- RLS
ALTER TABLE part_price_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users full access" ON part_price_history
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Verify
SELECT 'part_price_history table created successfully' AS status;
