-- ============================================================
-- STOCK MOVEMENTS TABLE
-- Tracks all stock inflow, outflow, and adjustments
-- Replaces overloading part_usage_logs for Part In
-- Run in Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Movement classification
  movement_type TEXT NOT NULL 
    CHECK (movement_type IN ('IN', 'OUT', 'ADJUST', 'RESTORE')),
    -- IN      = received from supplier
    -- OUT     = consumed by project
    -- ADJUST  = manual stock correction
    -- RESTORE = stock returned when part removed from project
  
  -- Part identification
  part_table_name TEXT NOT NULL,        -- e.g. 'mechanical_manufacture'
  part_id BIGINT NOT NULL,
  part_number TEXT NOT NULL,
  
  -- Quantity (positive for IN/RESTORE, negative for OUT, either for ADJUST)
  quantity INT NOT NULL,
  
  -- Stock levels at time of movement (for audit)
  stock_before INT,
  stock_after INT,
  
  -- IN-specific fields
  supplier_id BIGINT REFERENCES suppliers(id),
  supplier_name TEXT,
  po_number TEXT,
  
  -- OUT-specific fields
  project_name TEXT,
  project_id BIGINT REFERENCES projects(id),
  project_section_name TEXT,
  site_name TEXT,
  
  -- Common fields
  reference_notes TEXT,
  unit_price_at_movement NUMERIC(18, 2),
  currency TEXT DEFAULT 'INR',
  moved_by TEXT,                        -- user email
  moved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_sm_type ON stock_movements(movement_type);
CREATE INDEX idx_sm_part ON stock_movements(part_table_name, part_id);
CREATE INDEX idx_sm_part_number ON stock_movements(part_number);
CREATE INDEX idx_sm_date ON stock_movements(moved_at DESC);
CREATE INDEX idx_sm_project ON stock_movements(project_id) WHERE project_id IS NOT NULL;
CREATE INDEX idx_sm_supplier ON stock_movements(supplier_id) WHERE supplier_id IS NOT NULL;
CREATE INDEX idx_sm_in ON stock_movements(movement_type, moved_at DESC) WHERE movement_type = 'IN';
CREATE INDEX idx_sm_out ON stock_movements(movement_type, project_name) WHERE movement_type = 'OUT';

-- Comments
COMMENT ON TABLE stock_movements IS 'Complete audit trail of all stock changes: receipts, consumption, adjustments';
COMMENT ON COLUMN stock_movements.stock_before IS 'Stock quantity before this movement was applied';
COMMENT ON COLUMN stock_movements.stock_after IS 'Stock quantity after this movement was applied';

-- RLS
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users full access" ON stock_movements
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Verify
SELECT 'stock_movements table created successfully' AS status;
