-- ============================================================
-- REBUILD project_parts TABLE
-- Aligns SQL schema with frontend code (individual FK columns)
-- Adds price snapshot columns for BOM integrity
-- 
-- WARNING: This drops and recreates the table.
-- Only run if there is no data to preserve!
-- Run in Supabase SQL Editor
-- ============================================================

-- Step 1: Drop existing table and dependent objects
DROP TABLE IF EXISTS project_parts CASCADE;

-- Step 2: Recreate with individual FK columns + snapshot fields
CREATE TABLE project_parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_section_id BIGINT NOT NULL REFERENCES project_sections(id) ON DELETE CASCADE,
  
  -- ── Part References (exactly ONE must be non-null per row) ──
  mechanical_manufacture_id BIGINT REFERENCES mechanical_manufacture(id) ON DELETE SET NULL,
  mechanical_bought_out_part_id BIGINT REFERENCES mechanical_bought_out(id) ON DELETE SET NULL,
  electrical_manufacture_id BIGINT REFERENCES electrical_manufacture(id) ON DELETE SET NULL,
  electrical_bought_out_part_id BIGINT REFERENCES electrical_bought_out(id) ON DELETE SET NULL,
  pneumatic_bought_out_part_id BIGINT REFERENCES pneumatic_bought_out(id) ON DELETE SET NULL,
  
  -- ── Quantity ──
  quantity INT NOT NULL DEFAULT 0,
  
  -- ── Price Snapshot (captured at assignment time, never auto-updated) ──
  unit_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT DEFAULT 'INR',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  base_price_at_assignment NUMERIC(18, 2),      -- master base_price when this part was added
  supplier_name_at_assignment TEXT,               -- supplier name when this part was added
  
  -- ── Metadata ──
  reference_designator TEXT,
  notes TEXT,
  use_date_time TIMESTAMPTZ DEFAULT NOW(),
  assigned_at TIMESTAMPTZ DEFAULT NOW(),         -- when part was first added to this BOM
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ,
  
  -- ── Constraint: exactly one part FK must be set ──
  CONSTRAINT exactly_one_part_fk CHECK (
    (CASE WHEN mechanical_manufacture_id IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN mechanical_bought_out_part_id IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN electrical_manufacture_id IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN electrical_bought_out_part_id IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN pneumatic_bought_out_part_id IS NOT NULL THEN 1 ELSE 0 END) = 1
  )
);

-- Step 3: Indexes
CREATE INDEX idx_pp_section ON project_parts(project_section_id);
CREATE INDEX idx_pp_mm ON project_parts(mechanical_manufacture_id) WHERE mechanical_manufacture_id IS NOT NULL;
CREATE INDEX idx_pp_mbo ON project_parts(mechanical_bought_out_part_id) WHERE mechanical_bought_out_part_id IS NOT NULL;
CREATE INDEX idx_pp_em ON project_parts(electrical_manufacture_id) WHERE electrical_manufacture_id IS NOT NULL;
CREATE INDEX idx_pp_ebo ON project_parts(electrical_bought_out_part_id) WHERE electrical_bought_out_part_id IS NOT NULL;
CREATE INDEX idx_pp_pbo ON project_parts(pneumatic_bought_out_part_id) WHERE pneumatic_bought_out_part_id IS NOT NULL;

-- Step 4: Auto-update timestamp trigger
CREATE TRIGGER update_project_parts_updated_date
    BEFORE UPDATE ON project_parts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_date_column();

-- Step 5: Comments
COMMENT ON TABLE project_parts IS 'Links parts to project BOM sections with price snapshots';
COMMENT ON COLUMN project_parts.unit_price IS 'Price snapshot at time of assignment — does not change when master price changes';
COMMENT ON COLUMN project_parts.discount_percent IS 'Discount snapshot at time of assignment — does not change when master discount changes';
COMMENT ON COLUMN project_parts.base_price_at_assignment IS 'Master base_price at the moment this part was added to BOM';
COMMENT ON COLUMN project_parts.supplier_name_at_assignment IS 'Supplier name at the moment this part was added to BOM';
COMMENT ON COLUMN project_parts.assigned_at IS 'Timestamp when this part was first assigned to this BOM section';

-- Step 6: RLS
ALTER TABLE project_parts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users full access" ON project_parts
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Step 7: Verify
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'project_parts' 
  AND table_schema = 'public'
ORDER BY ordinal_position;
