-- ============================================================
-- SUPPLIERS TABLE
-- Step 2a from bom-deployment.md
-- ============================================================

-- Create suppliers table
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  address TEXT,
  payment_terms TEXT,
  notes TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Create index for supplier name search
CREATE INDEX IF NOT EXISTS idx_suppliers_name ON suppliers(name);

-- Add comment to table
COMMENT ON TABLE suppliers IS 'Stores supplier information for procurement';

-- Add comments to columns
COMMENT ON COLUMN suppliers.id IS 'Unique identifier for supplier';
COMMENT ON COLUMN suppliers.name IS 'Supplier company name';
COMMENT ON COLUMN suppliers.contact_person IS 'Primary contact person at supplier';
COMMENT ON COLUMN suppliers.email IS 'Contact email address';
COMMENT ON COLUMN suppliers.phone IS 'Contact phone number';
COMMENT ON COLUMN suppliers.address IS 'Business address';
COMMENT ON COLUMN suppliers.payment_terms IS 'Payment terms (e.g., Net 30, Net 60)';
COMMENT ON COLUMN suppliers.notes IS 'Additional notes about supplier';
COMMENT ON COLUMN suppliers.created_date IS 'Timestamp when record was created';
COMMENT ON COLUMN suppliers.updated_date IS 'Timestamp when record was last updated';

-- Create a trigger to automatically update updated_date
CREATE OR REPLACE FUNCTION update_updated_date_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_suppliers_updated_date 
    BEFORE UPDATE ON suppliers 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_date_column();

