-- ============================================================
-- PROJECTS TABLE
-- Step 2b from bom-deployment.md
-- ============================================================

-- Create projects table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name TEXT NOT NULL,
  project_number TEXT NOT NULL UNIQUE,
  customer TEXT,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'planning'
    CHECK (status IN ('planning', 'design', 'build', 'testing', 'completed', 'on_hold', 'cancelled')),
  start_date DATE,
  target_completion_date DATE,
  actual_completion_date DATE,
  mechanical_design_status TEXT DEFAULT 'not_started',
  ee_design_status TEXT DEFAULT 'not_started',
  pneumatic_design_status TEXT DEFAULT 'not_started',
  po_release_status TEXT DEFAULT 'not_started',
  part_arrival_status TEXT DEFAULT 'not_started',
  machine_build_status TEXT DEFAULT 'not_started',
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_number ON projects(project_number);
CREATE INDEX IF NOT EXISTS idx_projects_customer ON projects(customer);

-- Add comment to table
COMMENT ON TABLE projects IS 'Stores project information and tracking';

-- Add comments to columns
COMMENT ON COLUMN projects.id IS 'Unique identifier for project';
COMMENT ON COLUMN projects.project_name IS 'Name of the project';
COMMENT ON COLUMN projects.project_number IS 'Unique project number (e.g., PRJ-2024-001)';
COMMENT ON COLUMN projects.customer IS 'Customer or client name';
COMMENT ON COLUMN projects.description IS 'Project description';
COMMENT ON COLUMN projects.status IS 'Overall project status';
COMMENT ON COLUMN projects.start_date IS 'Project start date';
COMMENT ON COLUMN projects.target_completion_date IS 'Target completion date';
COMMENT ON COLUMN projects.actual_completion_date IS 'Actual completion date';
COMMENT ON COLUMN projects.mechanical_design_status IS 'Mechanical design phase status';
COMMENT ON COLUMN projects.ee_design_status IS 'Electrical/electronics design phase status';
COMMENT ON COLUMN projects.pneumatic_design_status IS 'Pneumatic design phase status';
COMMENT ON COLUMN projects.po_release_status IS 'Purchase order release status';
COMMENT ON COLUMN projects.part_arrival_status IS 'Part arrival status';
COMMENT ON COLUMN projects.machine_build_status IS 'Machine build status';
COMMENT ON COLUMN projects.created_date IS 'Timestamp when record was created';
COMMENT ON COLUMN projects.updated_date IS 'Timestamp when record was last updated';

-- Create a trigger to automatically update updated_date
CREATE OR REPLACE FUNCTION update_updated_date_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_projects_updated_date 
    BEFORE UPDATE ON projects 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_date_column();

