-- ============================================================
-- PROJECT SECTIONS TABLE
-- Step 2c from bom-deployment.md
-- ============================================================

-- Create project_sections table
CREATE TABLE IF NOT EXISTS project_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  section_name TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'planning',
  estimated_cost NUMERIC(18, 2),
  actual_cost NUMERIC(18, 2),
  start_date DATE,
  target_completion_date DATE,
  sort_order INT DEFAULT 0,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_sections_project ON project_sections(project_id);
CREATE INDEX IF NOT EXISTS idx_sections_status ON project_sections(status);
CREATE INDEX IF NOT EXISTS idx_sections_sort_order ON project_sections(sort_order);

-- Add comment to table
COMMENT ON TABLE project_sections IS 'Stores sections/divisions within projects';

-- Add comments to columns
COMMENT ON COLUMN project_sections.id IS 'Unique identifier for project section';
COMMENT ON COLUMN project_sections.project_id IS 'Foreign key to projects table';
COMMENT ON COLUMN project_sections.section_name IS 'Name of the project section';
COMMENT ON COLUMN project_sections.description IS 'Section description';
COMMENT ON COLUMN project_sections.status IS 'Section status';
COMMENT ON COLUMN project_sections.estimated_cost IS 'Estimated cost for this section';
COMMENT ON COLUMN project_sections.actual_cost IS 'Actual cost for this section';
COMMENT ON COLUMN project_sections.start_date IS 'Section start date';
COMMENT ON COLUMN project_sections.target_completion_date IS 'Target completion date for section';
COMMENT ON COLUMN project_sections.sort_order IS 'Display order for sections';
COMMENT ON COLUMN project_sections.created_date IS 'Timestamp when record was created';
COMMENT ON COLUMN project_sections.updated_date IS 'Timestamp when record was last updated';

-- Create a trigger to automatically update updated_date
CREATE OR REPLACE FUNCTION update_updated_date_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_project_sections_updated_date 
    BEFORE UPDATE ON project_sections 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_date_column();

