-- ============================================================
-- PARTS TABLES (5 types)
-- Step 2d from bom-deployment.md
-- ============================================================

-- ============================================================
-- TABLE: mechanical_manufacture (parts)
-- ============================================================
CREATE TABLE IF NOT EXISTS mechanical_manufacture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  material TEXT,
  finish TEXT,
  weight NUMERIC(10, 4),
  datasheet_url TEXT,
  image_path TEXT,       -- Supabase Storage path
  cad_file_url TEXT,
  pdm_file_path TEXT,
  vendor_part_number TEXT,
  po_number TEXT,
  pdf_path TEXT,         -- Supabase Storage path
  pdf2_path TEXT,        -- Supabase Storage path
  pdf3_path TEXT,        -- Supabase Storage path
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Add comments for mechanical_manufacture table
COMMENT ON TABLE mechanical_manufacture IS 'Mechanical parts that are manufactured in-house';
COMMENT ON COLUMN mechanical_manufacture.part_number IS 'Unique part number identifier';
COMMENT ON COLUMN mechanical_manufacture.berper_part_no IS 'BEPERP system part number';
COMMENT ON COLUMN mechanical_manufacture.total_amount IS 'Calculated: base_price * order_qty * (1 - discount_percent/100)';
COMMENT ON COLUMN mechanical_manufacture.total_stock IS 'Calculated: stock_quantity + received_qty';
COMMENT ON COLUMN mechanical_manufacture.image_path IS 'Path to image in Supabase Storage bucket';
COMMENT ON COLUMN mechanical_manufacture.pdf_path IS 'Path to primary PDF in Supabase Storage bucket';

-- Create indexes for mechanical_manufacture
CREATE INDEX IF NOT EXISTS idx_mm_part_number ON mechanical_manufacture(part_number);
CREATE INDEX IF NOT EXISTS idx_mm_supplier ON mechanical_manufacture(supplier_id);
CREATE INDEX IF NOT EXISTS idx_mm_stock ON mechanical_manufacture(stock_quantity) WHERE stock_quantity < min_stock_level;

-- ============================================================
-- TABLE: mechanical_bought_out (parts)
-- ============================================================
CREATE TABLE IF NOT EXISTS mechanical_bought_out (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  material TEXT,
  finish TEXT,
  weight NUMERIC(10, 4),
  datasheet_url TEXT,
  image_path TEXT,
  cad_file_url TEXT,
  pdm_file_path TEXT,
  vendor_part_number TEXT,
  po_number TEXT,
  pdf_path TEXT,
  pdf2_path TEXT,
  pdf3_path TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Add comments for mechanical_bought_out table
COMMENT ON TABLE mechanical_bought_out IS 'Mechanical parts that are purchased from suppliers';
COMMENT ON COLUMN mechanical_bought_out.total_amount IS 'Calculated: base_price * order_qty * (1 - discount_percent/100)';
COMMENT ON COLUMN mechanical_bought_out.total_stock IS 'Calculated: stock_quantity + received_qty';

-- Create indexes for mechanical_bought_out
CREATE INDEX IF NOT EXISTS idx_mbo_part_number ON mechanical_bought_out(part_number);
CREATE INDEX IF NOT EXISTS idx_mbo_supplier ON mechanical_bought_out(supplier_id);
CREATE INDEX IF NOT EXISTS idx_mbo_stock ON mechanical_bought_out(stock_quantity) WHERE stock_quantity < min_stock_level;

-- ============================================================
-- TABLE: electrical_manufacture (parts)
-- ============================================================
CREATE TABLE IF NOT EXISTS electrical_manufacture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  datasheet_url TEXT,
  image_path TEXT,
  cad_file_url TEXT,
  po_number TEXT,
  pdf_path TEXT,
  pdf2_path TEXT,
  pdf3_path TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Add comments for electrical_manufacture table
COMMENT ON TABLE electrical_manufacture IS 'Electrical/electronic parts that are manufactured in-house';
COMMENT ON COLUMN electrical_manufacture.total_amount IS 'Calculated: base_price * order_qty * (1 - discount_percent/100)';
COMMENT ON COLUMN electrical_manufacture.total_stock IS 'Calculated: stock_quantity + received_qty';

-- Create indexes for electrical_manufacture
CREATE INDEX IF NOT EXISTS idx_em_part_number ON electrical_manufacture(part_number);
CREATE INDEX IF NOT EXISTS idx_em_supplier ON electrical_manufacture(supplier_id);
CREATE INDEX IF NOT EXISTS idx_em_stock ON electrical_manufacture(stock_quantity) WHERE stock_quantity < min_stock_level;

-- ============================================================
-- TABLE: electrical_bought_out (parts)
-- ============================================================
CREATE TABLE IF NOT EXISTS electrical_bought_out (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  datasheet_url TEXT,
  image_path TEXT,
  cad_file_url TEXT,
  po_number TEXT,
  pdf_path TEXT,
  pdf2_path TEXT,
  pdf3_path TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Add comments for electrical_bought_out table
COMMENT ON TABLE electrical_bought_out IS 'Electrical/electronic parts that are purchased from suppliers';
COMMENT ON COLUMN electrical_bought_out.total_amount IS 'Calculated: base_price * order_qty * (1 - discount_percent/100)';
COMMENT ON COLUMN electrical_bought_out.total_stock IS 'Calculated: stock_quantity + received_qty';

-- Create indexes for electrical_bought_out
CREATE INDEX IF NOT EXISTS idx_ebo_part_number ON electrical_bought_out(part_number);
CREATE INDEX IF NOT EXISTS idx_ebo_supplier ON electrical_bought_out(supplier_id);
CREATE INDEX IF NOT EXISTS i
