-- ============================================================
-- PROJECT PARTS JUNCTION TABLE
-- Step 2e from bom-deployment.md
-- ============================================================

-- Create project_parts junction table
CREATE TABLE IF NOT EXISTS project_parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_section_id BIGINT NOT NULL REFERENCES project_sections(id) ON DELETE CASCADE,
  part_type TEXT NOT NULL
    CHECK (part_type IN (
      'mechanical_manufacture',
      'mechanical_bought_out',
      'electrical_manufacture',
      'electrical_bought_out',
      'pneumatic_bought_out'
    )),
  part_id BIGINT NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  unit_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT DEFAULT 'USD',
  reference_designator TEXT,
  notes TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_project_parts_section ON project_parts(project_section_id);
CREATE INDEX IF NOT EXISTS idx_project_parts_type ON project_parts(part_type);
CREATE INDEX IF NOT EXISTS idx_project_parts_part ON project_parts(part_type, part_id);

-- Add comment to table
COMMENT ON TABLE project_parts IS 'Junction table linking project sections to parts';

-- Add comments to columns
COMMENT ON COLUMN project_parts.id IS 'Unique identifier for project part assignment';
COMMENT ON COLUMN project_parts.project_section_id IS 'Foreign key to project_sections table';
COMMENT ON COLUMN project_parts.part_type IS 'Type of part (references one of the 5 parts tables)';
COMMENT ON COLUMN project_parts.part_id IS 'ID of the part in its respective parts table';
COMMENT ON COLUMN project_parts.quantity IS 'Quantity of this part used in the project section';
COMMENT ON COLUMN project_parts.unit_price IS 'Unit price at time of assignment';
COMMENT ON COLUMN project_parts.currency IS 'Currency for unit price';
COMMENT ON COLUMN project_parts.reference_designator IS 'Reference designator (e.g., R1, C2, U3)';
COMMENT ON COLUMN project_parts.notes IS 'Additional notes about this part usage';
COMMENT ON COLUMN project_parts.created_date IS 'Timestamp when record was created';
COMMENT ON COLUMN project_parts.updated_date IS 'Timestamp when record was last updated';

-- Create a trigger to automatically update updated_date
CREATE OR REPLACE FUNCTION update_updated_date_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_project_parts_updated_date 
    BEFORE UPDATE ON project_parts 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_date_column();

-- Create a function to validate that part_id exists in the correct parts table
CREATE OR REPLACE FUNCTION validate_project_part()
RETURNS TRIGGER AS $$
BEGIN
    -- Check if part exists in the specified table
    CASE NEW.part_type
        WHEN 'mechanical_manufacture' THEN
            PERFORM 1 FROM mechanical_manufacture WHERE id = NEW.part_id;
        WHEN 'mechanical_bought_out' THEN
            PERFORM 1 FROM mechanical_bought_out WHERE id = NEW.part_id;
        WHEN 'electrical_manufacture' THEN
            PERFORM 1 FROM electrical_manufacture WHERE id = NEW.part_id;
        WHEN 'electrical_bought_out' THEN
            PERFORM 1 FROM electrical_bought_out WHERE id = NEW.part_id;
        WHEN 'pneumatic_bought_out' THEN
            PERFORM 1 FROM pneumatic_bought_out WHERE id = NEW.part_id;
        ELSE
            RAISE EXCEPTION 'Invalid part_type: %', NEW.part_type;
    END CASE;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Part ID % does not exist in table %', NEW.part_id, NEW.part_type;
    END IF;
    
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to validate part references
CREATE TRIGGER validate_project_part_reference
    BEFORE INSERT OR UPDATE ON project_parts
    FOR EACH ROW
    EXECUTE FUNCTION validate_project_part();

