-- ============================================================
-- PURCHASE ORDERS TABLES
-- Step 2f from bom-deployment.md
-- ============================================================

-- ============================================================
-- TABLE: purchase_orders
-- ============================================================
CREATE TABLE IF NOT EXISTS purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_number TEXT NOT NULL UNIQUE,
  project_id BIGINT NOT NULL REFERENCES projects(id),
  supplier_id BIGINT NOT NULL REFERENCES suppliers(id),
  po_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'Pending'
    CHECK (status IN ('Pending', 'Sent', 'Confirmed', 'Partial', 'Received', 'Cancelled')),
  currency TEXT NOT NULL DEFAULT 'USD',
  grand_total NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_items INT NOT NULL DEFAULT 0,
  total_quantity INT NOT NULL DEFAULT 0,
  notes TEXT,
  terms TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_po_number ON purchase_orders(po_number);
CREATE INDEX IF NOT EXISTS idx_po_project ON purchase_orders(project_id);
CREATE INDEX IF NOT EXISTS idx_po_supplier ON purchase_orders(supplier_id);
CREATE INDEX IF NOT EXISTS idx_po_status ON purchase_orders(status);

-- Add comment to table
COMMENT ON TABLE purchase_orders IS 'Purchase order header information';

-- Add comments to columns
COMMENT ON COLUMN purchase_orders.id IS 'Unique identifier for purchase order';
COMMENT ON COLUMN purchase_orders.po_number IS 'Unique purchase order number';
COMMENT ON COLUMN purchase_orders.project_id IS 'Foreign key to projects table';
COMMENT ON COLUMN purchase_orders.supplier_id IS 'Foreign key to suppliers table';
COMMENT ON COLUMN purchase_orders.po_date IS 'Date when PO was created';
COMMENT ON COLUMN purchase_orders.status IS 'Current status of purchase order';
COMMENT ON COLUMN purchase_orders.currency IS 'Currency for all amounts in this PO';
COMMENT ON COLUMN purchase_orders.grand_total IS 'Total amount of all items in PO';
COMMENT ON COLUMN purchase_orders.total_items IS 'Total number of distinct items in PO';
COMMENT ON COLUMN purchase_orders.total_quantity IS 'Total quantity of all items in PO';
COMMENT ON COLUMN purchase_orders.notes IS 'Additional notes about PO';
COMMENT ON COLUMN purchase_orders.terms IS 'Payment and delivery terms';
COMMENT ON COLUMN purchase_orders.created_date IS 'Timestamp when record was created';
COMMENT ON COLUMN purchase_orders.updated_date IS 'Timestamp when record was last updated';

-- ============================================================
-- TABLE: purchase_order_items
-- ============================================================
CREATE TABLE IF NOT EXISTS purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  part_type TEXT NOT NULL,
  part_number TEXT NOT NULL,
  description TEXT,
  quantity INT NOT NULL DEFAULT 0,
  unit_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  project_part_id BIGINT REFERENCES project_parts(id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_poi_order ON purchase_order_items(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_poi_part_number ON purchase_order_items(part_number);
CREATE INDEX IF NOT EXISTS idx_poi_project_part ON purchase_order_items(project_part_id);

-- Add comment to table
COMMENT ON TABLE purchase_order_items IS 'Line items for purchase orders';

-- Add comments to columns
COMMENT ON COLUMN purchase_order_items.id IS 'Unique identifier for PO line item';
COMMENT ON COLUMN purchase_order_items.purchase_order_id IS 'Foreign key to purchase_orders table';
COMMENT ON COLUMN purchase_order_items.part_type IS 'Type of part (matches part_type in project_parts)';
COMMENT ON COLUMN purchase_order_items.part_number IS 'Part number for ordering';
COMMENT ON COLUMN purchase_order_items.description IS 'Part description';
COMMENT ON COLUMN purchase_order_items.quantity IS 'Quantity to order';
COMMENT ON COLUMN purchase_order_items.unit_price IS 'Unit price';
COMMENT ON COLUMN purchase_order_items.discount_percent IS 'Discount percentage applied';
COMMENT ON COLUMN purchase_order_items.total_amount IS 'Calculated: unit_price * quantity * (1 - discount_percent/100)';
COMMENT ON COLUMN purchase_order_items.project_part_id IS 'Optional foreign key to project_parts table if this item is from a project';

-- ============================================================
-- Triggers and functions
-- ============================================================

-- Create a trigger to automatically update updated_date for purchase_orders
CREATE OR REPLACE FUNCTION update_updated_date_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_purchase_orders_updated_date 
    BEFORE UPDATE ON purchase_orders 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_date_column();

-- Create a trigger to calculate total_amount for purchase_order_items
CREATE OR REPLACE FUNCTION calculate_poi_total_amount()
RETURNS TRIGGER AS $$
BEGIN
    NEW.total_amount = NEW.unit_price * NEW.quantity * (1 - COALESCE(NEW.discount_percent, 0) / 100);
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER calculate_poi_total_amount_on_insert
    BEFORE INSERT ON purchase_order_items
    FOR EACH ROW
    EXECUTE FUNCTION calculate_poi_total_amount();

CREATE TRIGGER calculate_poi_total_amount_on_update
    BEFORE UPDATE ON purchase_order_items
    FOR EACH ROW
    EXECUTE FUNCTION calculate_poi_total_amount();

-- Create a function to update PO summary when items change
CREATE OR REPLACE FUNCTION update_po_summary()
RETURNS TRIGGER AS $$
BEGIN
    -- Update grand_total, total_items, and total_quantity in purchase_orders
    UPDATE purchase_orders po
    SET 
        grand_total = (
            SELECT COALESCE(SUM(total_amount), 0)
            FROM purchase_order_items poi
            WHERE poi.purchase_order_id = po.id
        ),
        total_items = (
            SELECT COUNT(*)
            FROM purchase_order_items poi
            WHERE poi.purchase_order_id = po.id
        ),
        total_quantity = (
            SELECT COALESCE(SUM(quantity), 0)
            FROM purchase_order_items poi
            WHERE poi.purchase_order_id = po.id
        ),
        updated_date = NOW()
    WHERE po.id = (
        CASE 
            WHEN TG_OP = 'DELETE' THEN OLD.purchase_order_id
            ELSE NEW.purchase_order_id
        END
    );
    
    RETURN NULL;
END;
$$ language 'plpgsql';

-- Create triggers to update PO summary
CREATE TRIGGER update_po_summary_on_insert
    AFTER INSERT ON purchase_order_items
    FOR EACH ROW
    EXECUTE FUNCTION update_po_summary();

CREATE TRIGGER update_po_summary_on_update
    AFTER UPDATE ON purchase_order_items
    FOR EACH ROW
    EXECUTE FUNCTION update_po_summary();

CREATE TRIGGER update_po_summary_on_delete
    AFTER DELETE ON purchase_order_items
    FOR EACH ROW
    EXECUTE FUNCTION update_po_summary();

-- Create a function to update part stock when PO status changes to 'Received'
CREATE OR REPLACE FUNCTION update_part_stock_on_po_received()
RETURNS TRIGGER AS $$
BEGIN
    -- If status changed to 'Received', update stock quantities in parts tables
    IF NEW.status = 'Received' AND OLD.status != 'Received' THEN
        -- Update stock quantities for all parts in this PO
        UPDATE mechanical_manufacture mm
        SET stock_quantity = mm.stock_quantity + poi.quantity,
            updated_date = NOW()
        FROM purchase_order_items poi
        WHERE poi.purchase_order_id = NEW.id
          AND poi.part_type = 'mechanical_manufacture'
          AND poi.part_number = mm.part_number;
        
        UPDATE mechanical_bought_out mbo
        SET stock_quantity = mbo.stock_quantity + poi.quantity,
           
