-- ============================================================
-- PART USAGE LOGS & UPLOAD HISTORY
-- Step 2g from bom-deployment.md
-- ============================================================

-- ============================================================
-- TABLE: part_usage_logs
-- ============================================================
CREATE TABLE IF NOT EXISTS part_usage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name TEXT NOT NULL,
  site_name TEXT,
  use_date_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  part_number TEXT NOT NULL,
  part_table_name TEXT NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_part_usage_project ON part_usage_logs(project_name);
CREATE INDEX IF NOT EXISTS idx_part_usage_part_number ON part_usage_logs(part_number);
CREATE INDEX IF NOT EXISTS idx_part_usage_date ON part_usage_logs(use_date_time);
CREATE INDEX IF NOT EXISTS idx_part_usage_table ON part_usage_logs(part_table_name);

-- Add comment to table
COMMENT ON TABLE part_usage_logs IS 'Audit trail for part usage across projects';

-- Add comments to columns
COMMENT ON COLUMN part_usage_logs.id IS 'Unique identifier for usage log entry';
COMMENT ON COLUMN part_usage_logs.project_name IS 'Name of project where part was used';
COMMENT ON COLUMN part_usage_logs.site_name IS 'Site/location where part was used';
COMMENT ON COLUMN part_usage_logs.use_date_time IS 'Date and time when part was used';
COMMENT ON COLUMN part_usage_logs.part_number IS 'Part number that was used';
COMMENT ON COLUMN part_usage_logs.part_table_name IS 'Source table for the part (e.g., mechanical_manufacture)';
COMMENT ON COLUMN part_usage_logs.quantity IS 'Quantity used';
COMMENT ON COLUMN part_usage_logs.created_date IS 'Timestamp when log entry was created';

-- ============================================================
-- TABLE: json_excel_file_uploaded (upload history)
-- ============================================================
CREATE TABLE IF NOT EXISTS json_excel_file_uploaded (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT,
  date_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  json_content_type TEXT,
  json_data TEXT,
  excel_path TEXT,  -- Supabase Storage path (instead of VARBINARY)
  parts_processed INT NOT NULL DEFAULT 0,
  parts_added INT NOT NULL DEFAULT 0,
  parts_updated INT NOT NULL DEFAULT 0,
  errors INT NOT NULL DEFAULT 0,
  error_message TEXT
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_json_upload_user ON json_excel_file_uploaded(user_name);
CREATE INDEX IF NOT EXISTS idx_json_upload_date ON json_excel_file_uploaded(date_time);
CREATE INDEX IF NOT EXISTS idx_json_upload_type ON json_excel_file_uploaded(json_content_type);

-- Add comment to table
COMMENT ON TABLE json_excel_file_uploaded IS 'History of JSON/Excel file uploads for bulk part imports';

-- Add comments to columns
COMMENT ON COLUMN json_excel_file_uploaded.id IS 'Unique identifier for upload record';
COMMENT ON COLUMN json_excel_file_uploaded.user_name IS 'User who performed the upload';
COMMENT ON COLUMN json_excel_file_uploaded.date_time IS 'Date and time of upload';
COMMENT ON COLUMN json_excel_file_uploaded.json_content_type IS 'Type of content uploaded (e.g., JSON, Excel)';
COMMENT ON COLUMN json_excel_file_uploaded.json_data IS 'JSON content of the upload (if applicable)';
COMMENT ON COLUMN json_excel_file_uploaded.excel_path IS 'Path to Excel file in Supabase Storage bucket';
COMMENT ON COLUMN json_excel_file_uploaded.parts_processed IS 'Total number of parts processed in upload';
COMMENT ON COLUMN json_excel_file_uploaded.parts_added IS 'Number of new parts added';
COMMENT ON COLUMN json_excel_file_uploaded.parts_updated IS 'Number of existing parts updated';
COMMENT ON COLUMN json_excel_file_uploaded.errors IS 'Number of errors encountered during upload';
COMMENT ON COLUMN json_excel_file_uploaded.error_message IS 'Error message if upload failed';

-- ============================================================
-- Function to log part usage automatically
-- ============================================================

-- Function to create part usage log when parts are used in projects
CREATE OR REPLACE FUNCTION log_part_usage_from_project()
RETURNS TRIGGER AS $$
DECLARE
    project_record RECORD;
    part_record RECORD;
    part_table_name TEXT;
    part_number_val TEXT;
BEGIN
    -- Get project information
    SELECT p.project_name INTO project_record
    FROM projects p
    JOIN project_sections ps ON p.id = ps.project_id
    WHERE ps.id = NEW.project_section_id;
    
    -- Determine which parts table and get part number
    CASE NEW.part_type
        WHEN 'mechanical_manufacture' THEN
            SELECT part_number INTO part_record FROM mechanical_manufacture WHERE id = NEW.part_id;
            part_table_name := 'mechanical_manufacture';
        WHEN 'mechanical_bought_out' THEN
            SELECT part_number INTO part_record FROM mechanical_bought_out WHERE id = NEW.part_id;
            part_table_name := 'mechanical_bought_out';
        WHEN 'electrical_manufacture' THEN
            SELECT part_number INTO part_record FROM electrical_manufacture WHERE id = NEW.part_id;
            part_table_name := 'electrical_manufacture';
        WHEN 'electrical_bought_out' THEN
            SELECT part_number INTO part_record FROM electrical_bought_out WHERE id = NEW.part_id;
            part_table_name := 'electrical_bought_out';
        WHEN 'pneumatic_bought_out' THEN
            SELECT part_number INTO part_record FROM pneumatic_bought_out WHERE id = NEW.part_id;
            part_table_name := 'pneumatic_bought_out';
    END CASE;
    
    -- Create usage log entry
    INSERT INTO part_usage_logs (
        project_name,
        part_number,
        part_table_name,
        quantity,
        use_date_time
    ) VALUES (
        project_record.project_name,
        part_record.part_number,
        part_table_name,
        NEW.quantity,
        NOW()
    );
    
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to log part usage when parts are added to projects
CREATE TRIGGER log_part_usage_on_project_part_added
    AFTER INSERT ON project_parts
    FOR EACH ROW
    EXECUTE FUNCTION log_part_usage_from_project();

-- Create trigger to log part usage when project part quantity changes
CREATE TRIGGER log_part_usage_on_project_part_updated
    AFTER UPDATE ON project_parts
    FOR EACH ROW
    WHEN (OLD.quantity != NEW.quantity)
    EXECUTE FUNCTION log_part_usage_from_project();

