-- ============================================================
-- BOM MANAGER - COMPLETE DATABASE SETUP (COMBINED)
-- Copy and paste entire content into Supabase SQL Editor
-- Steps 2a-2g from bom-deployment.md - All 13 tables
-- ============================================================

-- ============================================================
-- 1. SUPPLIERS TABLE (Step 2a)
-- ============================================================
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  address TEXT,
  payment_terms TEXT,
  notes TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_suppliers_name ON suppliers(name);

-- ============================================================
-- 2. PROJECTS TABLE (Step 2b)
-- ============================================================
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name TEXT NOT NULL,
  project_number TEXT NOT NULL UNIQUE,
  customer TEXT,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'planning'
    CHECK (status IN ('planning', 'design', 'build', 'testing', 'completed', 'on_hold', 'cancelled')),
  start_date DATE,
  target_completion_date DATE,
  actual_completion_date DATE,
  mechanical_design_status TEXT DEFAULT 'not_started',
  ee_design_status TEXT DEFAULT 'not_started',
  pneumatic_design_status TEXT DEFAULT 'not_started',
  po_release_status TEXT DEFAULT 'not_started',
  part_arrival_status TEXT DEFAULT 'not_started',
  machine_build_status TEXT DEFAULT 'not_started',
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_number ON projects(project_number);

-- ============================================================
-- 3. PROJECT SECTIONS TABLE (Step 2c)
-- ============================================================
CREATE TABLE IF NOT EXISTS project_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  section_name TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'planning',
  estimated_cost NUMERIC(18, 2),
  actual_cost NUMERIC(18, 2),
  start_date DATE,
  target_completion_date DATE,
  sort_order INT DEFAULT 0,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sections_project ON project_sections(project_id);

-- ============================================================
-- 4. PARTS TABLES (5 types) (Step 2d)
-- ============================================================

-- 4a. mechanical_manufacture
CREATE TABLE IF NOT EXISTS mechanical_manufacture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  material TEXT,
  finish TEXT,
  weight NUMERIC(10, 4),
  datasheet_url TEXT,
  image_path TEXT,
  cad_file_url TEXT,
  pdm_file_path TEXT,
  vendor_part_number TEXT,
  po_number TEXT,
  pdf_path TEXT,
  pdf2_path TEXT,
  pdf3_path TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mm_part_number ON mechanical_manufacture(part_number);

-- 4b. mechanical_bought_out
CREATE TABLE IF NOT EXISTS mechanical_bought_out (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  material TEXT,
  finish TEXT,
  weight NUMERIC(10, 4),
  datasheet_url TEXT,
  image_path TEXT,
  cad_file_url TEXT,
  pdm_file_path TEXT,
  vendor_part_number TEXT,
  po_number TEXT,
  pdf_path TEXT,
  pdf2_path TEXT,
  pdf3_path TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mbo_part_number ON mechanical_bought_out(part_number);

-- 4c. electrical_manufacture
CREATE TABLE IF NOT EXISTS electrical_manufacture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  datasheet_url TEXT,
  image_path TEXT,
  cad_file_url TEXT,
  po_number TEXT,
  pdf_path TEXT,
  pdf2_path TEXT,
  pdf3_path TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_em_part_number ON electrical_manufacture(part_number);

-- 4d. electrical_bought_out
CREATE TABLE IF NOT EXISTS electrical_bought_out (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  datasheet_url TEXT,
  image_path TEXT,
  cad_file_url TEXT,
  po_number TEXT,
  pdf_path TEXT,
  pdf2_path TEXT,
  pdf3_path TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ebo_part_number ON electrical_bought_out(part_number);

-- 4e. pneumatic_bought_out
CREATE TABLE IF NOT EXISTS pneumatic_bought_out (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  beperp_part_no TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 0,
  order_qty INT NOT NULL DEFAULT 0,
  received_qty INT NOT NULL DEFAULT 0,
  lead_time TEXT,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock INT NOT NULL DEFAULT 0,
  specifications TEXT,
  manufacturer TEXT,
  manufacturer_part_number TEXT,
  port_size TEXT,
  operating_pr
